services:
  admin-monitor-suite:
    build:
        context: ../admin-monitor-suite
        target: production
    networks:
        - frontend-network
        - backend-network
    environment:
      - NODE_ENV=production